# Generated by Django 6.0.3 on 2026-04-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_user_name_play'),
        ('game', '0003_user_extra_plays_alter_user_name'),
    ]

    operations = [
    ]
