# Generated by Django 6.0.3 on 2026-04-28 21:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='date_played',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
